import json
import math
import os
import re
from typing import Dict, List

import litellm


def _stylometric(text: str) -> Dict:
    """Compute stylometric signals: sentence uniformity, vocab richness, punctuation density."""
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if len(s.strip()) > 10]
    if not sentences:
        return {"avg_sentence_length": 0, "vocabulary_richness": 0,
                "punctuation_density": 0, "sentence_uniformity": 0}

    wps = [len(re.findall(r"\b\w+\b", s)) for s in sentences]
    avg = sum(wps) / len(wps)
    std = math.sqrt(sum((x - avg) ** 2 for x in wps) / max(len(wps), 1))
    uniformity = 1 / (1 + std / max(avg, 1))

    all_words = re.findall(r"\b[a-z]+\b", text.lower())
    vocab_richness = len(set(all_words)) / max(len(all_words), 1)
    punct_density = len(re.findall(r"[,;:\(\)\-–—]", text)) / max(len(text), 1) * 100

    return {
        "avg_sentence_length": round(avg, 1),
        "vocabulary_richness": round(vocab_richness, 3),
        "punctuation_density": round(punct_density, 2),
        "sentence_uniformity": round(uniformity, 3),
    }


def _style_score(features: Dict) -> int:
    """Convert stylometric features to an AI-probability sub-score (0-50)."""
    score = 0
    if features["sentence_uniformity"] > 0.7:
        score += 20
    elif features["sentence_uniformity"] > 0.5:
        score += 10
    if 18 <= features["avg_sentence_length"] <= 28:
        score += 15
    if 0.35 <= features["vocabulary_richness"] <= 0.65:
        score += 10
    if features["punctuation_density"] < 1.5:
        score += 5
    return score


async def detect_ai_text(text: str) -> Dict:
    """Detect AI-authorship probability using stylometric analysis + Gemini classifier."""
    sample = text[:3000]
    features = _stylometric(sample)
    style_sub = _style_score(features)

    prompt = f"""Analyse the following text and estimate the probability that it was generated by an AI language model (ChatGPT, Gemini, Claude, etc.) rather than written by a human.

Look for these AI signals:
- Overly formal, structured language
- Repetitive transitional phrases ("Furthermore", "Moreover", "In conclusion")
- Lack of personal anecdotes, colloquialisms, or typos
- Uniform sentence structure with little variation
- "Balanced" constructions hedging every point

Text:
"{sample}"

Respond ONLY with valid JSON (no markdown):
{{"ai_probability":<0-100>,"label":"LIKELY_HUMAN"|"AI_ASSISTED"|"LIKELY_AI","signals":["signal1","signal2","signal3"]}}"""

    llm_score = 50
    label = "AI_ASSISTED"
    signals: List[str] = []

    try:
        gemini_key = os.getenv("GEMINI_API_KEY")
        groq_key = os.getenv("GROQ_API_KEY")
        
        if gemini_key:
            model = "gemini/gemini-1.5-flash-latest"
            api_key = gemini_key
        elif groq_key:
            model = "groq/llama-3.3-70b-versatile"
            api_key = groq_key
        else:
            raise ValueError("Neither GEMINI_API_KEY nor GROQ_API_KEY is configured.")

        resp = litellm.completion(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            api_key=api_key,
            temperature=0.1,
            max_tokens=300,
        )
        raw = resp.choices[0].message.content.strip()
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
        parsed = json.loads(raw)
        llm_score = int(parsed.get("ai_probability", 50))
        label = parsed.get("label", "AI_ASSISTED")
        signals = parsed.get("signals", [])
    except Exception:
        signals = ["Analysis inconclusive"]

    # Blend: 35% stylometric, 65% LLM
    final = round(0.35 * (style_sub / 50 * 100) + 0.65 * llm_score)
    final = max(0, min(100, final))

    if final < 30:
        label = "LIKELY_HUMAN"
    elif final < 65:
        label = "AI_ASSISTED"
    else:
        label = "LIKELY_AI"

    return {
        "score": final,
        "label": label,
        "signals": signals[:5],
        "stylometricFeatures": features,
    }
